FROM node:22-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

ENV NODE_ENV=development
ENV NUXT_TELEMETRY_DISABLED=1

EXPOSE 3001

CMD ["npm", "run", "dev"]